[build]
  publish = "."
  command = "echo 'No build needed'"

[[headers]]
  for = "/admin/config.yml"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Cache-Control = "no-cache"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
