[build]
  publish = "."
  command = "echo 'No build needed'"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Cache-Control = "no-cache"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true
